version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    depends_on:
      - db
    command: npm run start:dev

volumes:
  db:
  redis:
