version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: npm run start:dev

volumes:
  db:
